server:
  port: 8091

business:
  behavior:
    monitor:
      config:
        # 状态；true = 开启、false 关闭
        enabled: true
        # redis host
        host: 127.0.0.1
        # redis port
        port: 16379

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
